platform :ios, '8.0'
use_frameworks!

workspace 'SexyWaffles'
xcodeproj 'SexyWaffles.xcodeproj'

inhibit_all_warnings!

target 'SexyWaffles' do
    xcodeproj 'SexyWaffles.xcodeproj'
    pod 'ActorSDK-iOS'
    pod 'HockeySDK', '~> 4.1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end