platform :ios, '8.0'
use_frameworks!

workspace 'SexyWaffles'
xcodeproj 'SexyWaffles.xcodeproj'

inhibit_all_warnings!

target 'SexyWaffles' do
    xcodeproj 'SexyWaffles.xcodeproj'
    pod 'ActorSDK-iOS'
    pod 'HockeySDK', '~> 4.1.0'
end
